difficulty_list = ["Easy", "Medium", "Hard", "Expert"]
new_sudoku = "開啟一場新的數獨遊戲"
new_sudoku_difficulty = "難度選項 (0:Easy, 1:Medium, 2:Hard, 3:Expert)"
start_sudoku = "繼續上次的遊玩紀錄"
cheat = "等等... 先不要..."
help_command = "開啟指令說明"
help_embed_field1 = "Continue the game you have started. It won't create a new game if the user has not started a game."
help_embed_field2 = "Create a new game. The user must set difficulty level, which have 4 options: Easy (0), Medium (1), Hard (2), and Expert (3). It will delete existing game data after warning the user."
help_embed_field3 = "Show the answer of the game. The user must create a new game before using this function. A new game will not be created if the user has not already started one. This function will over write existing game data."